### ISSUE TITLE
How to build a libcaffe.so for 32 bit arm

### ISSUE THREAD

**Issue by dusen17** [sh1r0/caffe-android-lib#106]
I just run a caffe-android-demo on a 32bit device .when i start the app ,i got a error message like this:

`demo E/art: dlopen("/vendor/lib/libcaffe.so", RTLD_LAZY) failed: dlopen failed: "/vendor/lib/libcaffe.so" is 64-bit instead of 32-bit
04-07 14:55:20/com.sh1r0.caffe_android_demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.sh1r0.caffe_android_demo, PID: 19386
                                                                              java.lang.UnsatisfiedLinkError: dlopen failed: "/vendor/lib/libcaffe.so" is 64-bit instead of 32-bit
                                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:383)
                                                                                  at java.lang.System.loadLibrary(System.java:997)
                                                                                  at com.sh1r0.caffe_android_demo.MainActivity.<clinit>(MainActivity.java:57)
                                                                                  at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                  at java.lang.Class.newInstance(Class.java:1606)
                                                                                  at android.app.Instrumentation.newActivity(Instrumentation.java:1069)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                                                  at android.app.ActivityThread.access$1200(ActivityThread.java:163)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:137)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5595)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)` 

so how can i build a libcaffe.so for 32 bit arm. any idea will be appreciated

**Comment by sh1r0** [comment]
Please follow the build steps [here](https://github.com/sh1r0/caffe-android-lib#build), thanks.

**Comment by sh1r0** [comment]
Please refer to the latest commit (b9b0ba7), I just added docker support for building this project.
