### ISSUE TITLE
Error during ./build.py $(NDK_PATH) 

### ISSUE THREAD

**Issue by raretomato** [sh1r0/caffe-android-lib#12]
I tried to solve the this error, but I can not find the solution for this error.
I checked the issue #8 , so I tried "g:/test/android-ndk-r10e", g:/test/android-ndk-r10e, "g:\test\android-ndk-r10e".

My Os is windows 8.1 64bit.

![image](https://cloud.githubusercontent.com/assets/12879406/8147502/afbb9cb0-12a8-11e5-97a0-9e382b178709.png)

G:\test\caffe-android-lib>set NDK_ROOT=g:/test/android-ndk-r10e

G:\test\caffe-android-lib>echo %NDK_ROOT%
g:/test/android-ndk-r10e

G:\test\caffe-android-lib>build.py %NDK_ROOT%
Traceback (most recent call last):
  File "G:\test\caffe-android-lib\build.py", line 111, in <module>
    main(sys.argv[1:])
  File "G:\test\caffe-android-lib\build.py", line 101, in main
    setup()
  File "G:\test\caffe-android-lib\build.py", line 31, in setup
    call(['curl', '-O', PROTOBUF_URL])
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]

G:\test\caffe-android-lib>build.py $(NDK_ROOT)
Traceback (most recent call last):
  File "G:\test\caffe-android-lib\build.py", line 111, in <module>
    main(sys.argv[1:])
  File "G:\test\caffe-android-lib\build.py", line 101, in main
    setup()
  File "G:\test\caffe-android-lib\build.py", line 31, in setup
    call(['curl', '-O', PROTOBUF_URL])
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by sh1r0** [comment]
In Windows, you need to manually install *nix command tools (e.g., curl, tar, etc.) via cygwin or other 3rd-party tools.

**Comment by raretomato** [comment]
Thank you for fast answer!

But there is also error. I am not used to cyg and python :(..

Please help me.

![image](https://cloud.githubusercontent.com/assets/12879406/8147601/61ad2a24-12ae-11e5-9400-33ccfaa9aa87.png)

**Comment by raretomato** [comment]
I change the path of the python, but I can show same error..
Should I install other program? 

![image](https://cloud.githubusercontent.com/assets/12879406/8147615/5575c954-12af-11e5-840d-d12ad493c00f.png)

**Comment by raretomato** [comment]
I find the reason of the errors.

When I setup the Cygwin, I choose the default mode, but It contains a few functions.
So, after I setup the all of the functions, I can successfully build the program.

![image](https://cloud.githubusercontent.com/assets/12879406/8147715/e8106c4c-12b4-11e5-8cd2-9b6fb3e56f06.png)
