### ISSUE TITLE
error ndk-build

### ISSUE THREAD

**Issue by venturozzaccio** [sh1r0/caffe-android-lib#17]
Hi! After installing cygwin64 with tar and curl I still got this problem (Windows 10 64bit).

Bonaventura@Ventura /cygdrive/c/Users/Bonaventura/Desktop/caffe-android-lib-master/caffe-android-lib-master
$ ./build.py C:\Users\Bonaventura\AppData\Local\Android\sdk1\ndk-bundle
Traceback (most recent call last):
  File "./build.py", line 111, in <module>
    main(sys.argv[1:])
  File "./build.py", line 106, in main
    build_protobuf(ndk_build_)
  File "./build.py", line 64, in build_protobuf
    ndk_build()
  File "./build.py", line 55, in ndk_build
    call(['ndk-build', '-j', str(jobs)])
  File "C:\Users\Bonaventura\Anaconda\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Users\Bonaventura\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Users\Bonaventura\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] Impossibile trovare il file specificato

My ndk-build works

$ ndk-build
Android NDK: Could not find application project directory !
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
/cygdrive/c/Users/Bonaventura/AppData/Local/Android/sdk1/ndk-bundle/build/core/build-local.mk:143: *** Android NDK: Aborting    .  Arresto.

**Comment by Keyurpatel93** [comment]
I am also receiving a similar error. Any idea on how I should go about fixing this? Thanks

Traceback (most recent call last):
  File "./build.py", line 111, in <module>
    main(sys.argv[1:])
  File "./build.py", line 106, in main
    build_protobuf(ndk_build_)
  File "./build.py", line 64, in build_protobuf
    ndk_build()
  File "./build.py", line 55, in ndk_build
    call(['ndk-build', '-j', str(jobs)])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by venturozzaccio** [comment]
I succesfully installed. Are you on Windows or Linux? Did you use git or
just manually unzip the package? Do you use the NDK_PATH variable or
manually write path?
Il 18/set/2015 03:01, "Keyurpatel93" <notifications@github.com> ha scritto:

**Comment by sh1r0** [comment]
I've tested on Mac OSX, Ubuntu and Windows. If you run under cygwin, you should try to use cygwin-like path, for example, `./build.py /cygdrive/d/android-ndk-r10e/`. I use git and follow my [instructions](https://github.com/sh1r0/caffe-android-lib#build). You can use either `./build.py $(NDK_PATH)` or `./build.py <path_to_ndk>`. (You need to export NDK_PATH first.)

**Comment by sh1r0** [comment]
And there is a closed issue (https://github.com/sh1r0/caffe-android-lib/issues/12) related to building on Windows.
