### ISSUE TITLE
Error in Build (Mac)

### ISSUE THREAD

**Issue by Keyurpatel93** [sh1r0/caffe-android-lib#18]
I am also receiving a similar error as the other post. Any idea on how I should go about fixing this? Thanks
I am trying to install this on a Macbook running Yosemite.
I also manually extracted the boost file and put it inside the Boost-for-Android folder.

Traceback (most recent call last):
File "./build.py", line 111, in 
main(sys.argv[1:])
File "./build.py", line 106, in main
build_protobuf(ndk_build_)
File "./build.py", line 64, in build_protobuf
ndk_build()
File "./build.py", line 55, in ndk_build
call(['ndk-build', '-j', str(jobs)])
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
return Popen(popenargs, *kwargs).wait()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in init
errread, errwrite)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by sh1r0** [comment]
There is no need to build boost anymore, I forgot to remove the `Boost-for-Android` submodule. I have a fresh try and build without errors by using `./build.py <path_to_ndk>` (e.g., ./build.py ~/android-ndk-r9/).

**Comment by Keyurpatel93** [comment]
Hey

Thanks for the quick reply, I was doing something really stupid on my send and got it working the next morning when I woke up. I have a question regarding feature extraction. Do you know if we can simply obtain the feature vector that is outputted? I will write my own predict function, however in order to do this I need the raw extracted feature from an input image.

Thanks

**Comment by sh1r0** [comment]
Please refer to https://github.com/sh1r0/caffe-android-lib/issues/13.
