### ISSUE TITLE
Error during ./build.py $(NDK_PATH)

### ISSUE THREAD

**Issue by shreygarg** [sh1r0/caffe-android-lib#8]
whenever i try running ./build.py $(NDK_PATH) I get the following error :

Traceback (most recent call last):
  File "./build.py", line 131, in <module>
    main(sys.argv[1:])
  File "./build.py", line 120, in main
    setup()
  File "./build.py", line 36, in setup
    call(['curl', '-O', PROTOBUF_URL])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Any help to solve this would be appreciated .

**Comment by sh1r0** [comment]
Use `./build.py <path to your NDK>` instead, if you do not export `NDK_PATH`.
(`build.py -h` shows the help message.)
